In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.random.rand(2)

array([0.44148438, 0.48626152])

In [14]:
np.random.rand(5,5)

array([[0.28635744, 0.69029536, 0.61313689, 0.54053386, 0.78899219],
       [0.22471564, 0.22094001, 0.30814962, 0.21930377, 0.71346581],
       [0.62072405, 0.39405049, 0.9238906 , 0.40168053, 0.5941142 ],
       [0.3844375 , 0.87612621, 0.6215428 , 0.11138262, 0.52732025],
       [0.77012406, 0.30615818, 0.81546372, 0.98896091, 0.92656409]])

In [15]:
np.random.randn(5,5)

array([[ 1.61849338,  0.63098087,  2.26407352, -0.92076541, -1.53383029],
       [-0.45225172,  0.14605911,  0.94267495,  0.24941369, -2.47380434],
       [ 0.26638362,  0.61392622, -1.83675848, -0.11728332,  0.03132198],
       [-1.03752313, -1.00959957,  2.32242988, -1.13786926,  0.21055228],
       [ 1.23101353,  1.49773615, -1.91840976, -0.80371285,  0.08526789]])

In [17]:
np.random.randint(1,100,10)

array([31, 39, 22, 45, 20, 42, 43, 17, 59,  7])

In [18]:
np.random.randint(1,100,10).reshape(2,5)

array([[21, 29, 29,  8, 85],
       [64, 85, 27,  2, 11]])

In [19]:
ranarr = np.random.randint(0,50,10)

In [20]:
ranarr

array([42, 30, 48, 10, 42,  6, 44, 13, 12, 49])

In [21]:
ranarr.max()

49

In [22]:
ranarr.min()

6

In [23]:
ranarr.argmax()

9

In [24]:
ranarr.argmin()

5

In [26]:
ranarr.shape

(10,)

In [29]:
ranarr.reshape(1,10)

array([[42, 30, 48, 10, 42,  6, 44, 13, 12, 49]])

In [30]:
ranarr.reshape(1,10).shape

(1, 10)

In [32]:
ranarr.dtype

dtype('int64')

In [33]:
ranarr.reshape(1,10).dtype

dtype('int64')

In [34]:
arr = np.arange(0,11)

In [35]:
arr[8]

8

In [36]:
arr[1:5]

array([1, 2, 3, 4])

In [37]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [38]:
arr = np.arange(0,11)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [41]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [42]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [43]:
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [44]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [45]:
arr_2d[2]

array([35, 40, 45])

In [46]:
arr_2d[1][0]

20

In [47]:
arr_2d[:2,1:]arr2d[[2,4,6,8]]

array([[10, 15],
       [25, 30]])

In [48]:
arr2d = np.zeros((10,10))

In [49]:
arr_length = arr2d.shape[1]
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [50]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [51]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [53]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [54]:
arr = np.arange(0,10)

In [55]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [56]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [57]:
arr/arr

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [58]:
1/arr

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [59]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [60]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [61]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [62]:
np.max(arr)

9

In [63]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [64]:
np.log(arr)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])