In [12]:
import tensorflow as tf

In [13]:
print(tf.__version__)

1.12.0


In [14]:
hello = tf.constant('Hello')

In [15]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [16]:
world = tf.constant('World')

In [17]:
result = hello + world

In [18]:
result

<tf.Tensor 'add_2:0' shape=() dtype=string>

In [9]:
type(result)

tensorflow.python.framework.ops.Tensor

In [20]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [21]:
result

b'HelloWorld'

In [22]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [23]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [24]:
tensor_1 + tensor_2

<tf.Tensor 'add_5:0' shape=() dtype=int32>

In [44]:
with tf.Session() as sess:
    result = sess.run(tensor_1+tensor_2)
result

3

In [45]:
const = tf.constant(10)

In [46]:
fill_mat = tf.fill((4,4),10)

In [47]:
myzeros = tf.zeros((4,4))

In [48]:
myones = tf.ones((4,4))

In [49]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [50]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [51]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [52]:
# Only run this cell once!
sess = tf.InteractiveSession()

/home/aayush/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [53]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.6441969  -0.03665436  0.7983242   0.79944193]
 [-0.06519776  0.07357431  0.52652013  0.18905503]
 [ 0.3149596  -0.32854712 -0.18777913 -0.3476057 ]
 [ 0.3730971   0.78870076  0.15939842  0.76789767]]


[[0.89730203 0.8046032  0.17641199 0.18897331]
 [0.9396628  0.06315577 0.36002827 0.54301584]
 [0.6388546  0.9664587  0.6597525  0.1656357 ]
 [0.6932086  0.5034051  0.26469016 0.5420637 ]]




In [54]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [55]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [56]:
b = tf.constant([[10],[100]])

In [57]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [58]:
result = tf.matmul(a,b)

In [59]:
result.eval()

array([[210],
       [430]], dtype=int32)